apiVersion: v1
kind: Secret
metadata:
  name: cifs-secret
  namespace: longhorn
type: Opaque
data:
  CIFS_USERNAME: {{ .Values.cifs.username | b64enc }}
  CIFS_PASSWORD: {{ .Values.cifs.password | b64enc }}
