receivers:
  - name: 'default'
    webhook_configs:
      - url: http://alertmanager-discord-alerts-noise:9094
  - name: 'discord_alerts'
    webhook_configs:
      - url: http://alertmanager-discord-alerts:9094

route:
  receiver: default
  group_by: ['alertname', 'job', category]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 8h

  routes:
  - match:
      severity: critical
    receiver: 'discord_alerts'
    continue: false