apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
  namespace: argocd
  labels:
    app: {{ include "argo-cd.name" . }}
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "argo-cd"
data:
  key.txt: {{ .Values.age.age_key | b64enc }}