apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-operator-loadtest
  labels:
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
{{- range $path, $_ :=  .Files.Glob  "tests/**.js" }}
{{ $path | trimPrefix "tests/" | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
