kube-prometheus-stack:
    alertmanager:
        config:
            receivers:
                - name: ENC[AES256_GCM,data:l7Ab5QXDhg==,iv:3Jh0jD1zZsGChrM4NsN5MGyuffrC/Ic9UeFC/tejQvM=,tag:bHPHCX6VJTJg9n/vM2BllA==,type:str]
                  discord_configs:
                    - send_resolved: ENC[AES256_GCM,data:Q/DsLA==,iv:TvJcvV5Dh+2uAr3Nrw4aaDtWm5BU7JR6n3MvLdurC6w=,tag:4bGf8Qxq1e2bRzDIPJwBXA==,type:bool]
                      http_config:
                        follow_redirects: ENC[AES256_GCM,data:aYrPHQ==,iv:6X/RXXYWkt108KoYeYg5JLnUUnBNzvdRGZ1sOF6+9CY=,tag:xiApdoWo2TlrxT7EgolFAg==,type:bool]
                        enable_http2: ENC[AES256_GCM,data:Per9DQ==,iv:m5bmb1lkl5gR14J8jVksBqe2JZFL8CWfWmrPr+pTHhE=,tag:ZTf2nmzmYUBJQc8jhABJKw==,type:bool]
                      webhook_url: ENC[AES256_GCM,data:V2L0IbDkpEg+keop7tcDkV87WhcO9j/m6cDlakx6jIIbcA4L2UzOW2vmHSiN4igyZedQ7TyiL9Mr9YBUnQM9KJk5pKsPCThdRhxCJn7ApvUzBGv++RSC3jYDOuP+cy31Kw9hqYG903uCUXoLFEAkxVzQFag0B54aeQ==,iv:VHBwOpsmIaA8B5hJ1mHP/7JvhG8QwwYWtb5+nqVC3LM=,tag:KqfyG4jhAt0zill3sn7iVQ==,type:str]
                      title: ENC[AES256_GCM,data:YTfCUTjanLcQrWcCunJzQh8HQFgocm4o08iXcSh+zmbSpG+3HAXDAw==,iv:efx15/k/3xwOmQ4RlH0zS8oqjWnB/8eGResCJOfi1Tg=,tag:ifi4yy9gytKvWPnBcSLAEA==,type:str]
                      message: ENC[AES256_GCM,data:j0WCiScNgc5wV5x9Vg9u3AH6bF+nvh0/cObvjwhU9yX+k6GrTZUjozTw,iv:jRa58qWM/nWrmfUjcZtP4byQH65k7wRmLbH5gl3hyoo=,tag:pSr5UNh1lxEzzMgJmbmZ0A==,type:str]
                - name: ENC[AES256_GCM,data:MLlAjXTtcfn3lcrZZEA=,iv:LXVpVj8RW1JWTkaN1Byi6FzdvB8wCP+LzDwHdkBtBD4=,tag:jYGnPYitgKpMMM0vZd+oLQ==,type:str]
                  discord_configs:
                    - send_resolved: ENC[AES256_GCM,data:09tk4Q==,iv:v/BxtwDQtKef8GnFAQFZdRssYVL0kZ2UFzJSaKYueEY=,tag:9L4AvtALqdpfwb0T2pjhew==,type:bool]
                      http_config:
                        follow_redirects: ENC[AES256_GCM,data:egL7UA==,iv:fZYKb5pxAjm+wmbIoaHjewXDd01lOM973ZdIhE2eY2I=,tag:ZQmojz45l9RBqE2eD+VoDw==,type:bool]
                        enable_http2: ENC[AES256_GCM,data:bYlLTA==,iv:jMo+zpJ0a7cyUwiwcHYKV0yBO1uyqPstzRJcWwNVkkg=,tag:8XHEICHB6fMWS+2SE4pvNw==,type:bool]
                      webhook_url: ENC[AES256_GCM,data:DziTukCXfrnqZAn6n1h3f+5Ufvk0Ecn3A104gKQXebRkwwILC6LPC+zKoU7k1yEengLI9jtm+5J6EypM07f656+jWqeLcnG4IRzConxHURYj5Ji+i4IF8AEdpJaVpfTetAbjP6PxONi5oHdXRR46/ZTZQBcnZg1IPw==,iv:dLU6f3foLqfxaPzZRLdHsY91HneDCAhJFxlRt8/WlU0=,tag:sj2RgKg4ySlATJbJrQmOyQ==,type:str]
                      title: ENC[AES256_GCM,data:lAEprkJcWMg4n2x2o5rUxZo54l7TH8AVtiV9qHifv5xR/tBXF9yUbQ==,iv:epoo4rRTcBBw9Yc9SsIMOuE8UxihkBNh3wVWXGD8Ztc=,tag:fUA/Oia9y2DpleB6Odqieg==,type:str]
                      message: ENC[AES256_GCM,data:FeBEMGs5ovRI0kdiXCSG8tpt4BB+Dkih0gSAEvKD+3peFT5nbFT9f1Xw,iv:t5c0Qn767TNIv++bd1rMA+p2MsfgFkIkVRsMvRODqPA=,tag:myOlQPSpHgpqe9pVgDgxkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNExaQjNtRmN5cVpZZUUv
            azF6SVVSaUlPelF3UTJERDFqeC93TEh6clFZCnlFYXBBR1Q1RnY5NmtrcEp6SDVa
            d3MxSUF5RXZlTzkrbjdHMzBUenVXMDgKLS0tIEJWVVJ2MS95NnBoK0ZkTFhockM5
            ZXhYNU1va2lsVmRtWmNTOEJhSTcwT1UKhcgxa7LCFfK2EvxLAqbN1xIZX6A+HH03
            v3Aq7+AKMY6rqA6FooVaimftTY9UUpu5awrcPIRXlcCwl5eS+m0mzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T07:35:48Z"
    mac: ENC[AES256_GCM,data:t1JabiLvSS9JHxOz46NeH8lyct62j+ajTOYXAFZ6C618r26f/Adh1ZPO9+405vAOwPS5KxBxEhWdrYPJVXfPNgSHA9DXWHdX3ipm7fWYn/hRYNUNpzTfo9oAp6h8P0GQpXgachprfr5K0OCMWIozQp1W8ABLExVVrjRInQlQKB8=,iv:3AuBUCeSTV4S/7Y3p4YpctOxOHmZ1esvcZVzWf8H1C8=,tag:qvOa+3UiuCVgQxiS746q6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
