kube-prometheus-stack:
    alertmanager:
        config:
            receivers:
                - name: ENC[AES256_GCM,data:Me4s2iaLlQ==,iv:fx0XDAaVc3R1s3dfnwMMJTFcN2A/aUzSBFfm/mjZ4IU=,tag:53Mbt8HUnRd3AOmfTXDYBw==,type:str]
                  discord_configs:
                    - send_resolved: ENC[AES256_GCM,data:c3buFA==,iv:R4SLYODMB08WHia2ViwlIncMY64SIVKr9UyIWeSc6G0=,tag:i8oE63+N3ZWRTin7SkeIUA==,type:bool]
                      http_config:
                        follow_redirects: ENC[AES256_GCM,data:kRhWFQ==,iv:SG3+usEHXQBIJM3kzRyT3aEa8OsZ89CdSIUIIINlqck=,tag:5+gvRMUnaQr2Q3ven1ylzg==,type:bool]
                        enable_http2: ENC[AES256_GCM,data:dLWiMQ==,iv:2RZLN1vn9846lUDq/pCoREnBYue1B2gufHnD9YjRhmo=,tag:h8LJWaGM+Ye7YKGd3rt/6w==,type:bool]
                      webhook_url: ENC[AES256_GCM,data:97HUTPpud/xwyn4MzeBbbOk3pZqfMYpEQLDZ2VWVtLeVCY6BYBll6Q4SM47bn+8wXRFkPc9GyM0qRFLDoTbAHTc33FsZwi4XYZXA/NY9HW5yOvmABHz05tCnCCCmb5RGeJ2Acj14AkgnxvQNU6hg1JSanVKRbni1hQ==,iv:PHaFYPrH2NWyubRy8Zk3VYLeZMmwqWveFwYG8c3TdOI=,tag:uV4yy6Bwr2/8Mk12rOl4bQ==,type:str]
                      title: ENC[AES256_GCM,data:s8jejt9EM1eZsaof5r0famxfkmL0wNDm2WUk/Y3WXCMfkNF4KN3Pew==,iv:qCVeaOkEAXCJ0Ah2FRO3CBfm1ra81PERPupYpR4j4c0=,tag:2eylwbX12zX8Drcz1xtFbA==,type:str]
                      message: ENC[AES256_GCM,data:QM113JoQgdPLZ7CJNTfXzRlrCiobZb9bADWQ3fJUYbGqe4//ZHASsyAE,iv:7jdivJrFE7Yr2vLVwFwOfHY0uXlUyh5AOr5dnce3pVo=,tag:7MgGgh7OCrs4MyvBUQBRhg==,type:str]
                - name: ENC[AES256_GCM,data:/iCRcPiB2xo0A89VPV4=,iv:ZJzukHk75JjrZeOApdPqN6rqw1eQqPRmz611K+5UtNM=,tag:qsfOGRw0d2Rmu6g0FVuCgQ==,type:str]
                  discord_configs:
                    - send_resolved: ENC[AES256_GCM,data:CsDlOw==,iv:xZ1xXBxZAcDnaxIN9PVM+ASf8jQ3DdM+ninLljDOeGg=,tag:nI2c8gG6Ac/ob/OA4HRTjg==,type:bool]
                      http_config:
                        follow_redirects: ENC[AES256_GCM,data:z3tXaQ==,iv:CnSL7aHF1MfZXSrYTRwAkPPB/S50XYQtMqf+PRIVT6E=,tag:x2N9iVyxjCvcpUWhB9M0/g==,type:bool]
                        enable_http2: ENC[AES256_GCM,data:Px3CPw==,iv:K+NSEsxHUM7czMhMa+b5A3znkheStu5FkvPJAdzWfuo=,tag:wtk26kfN7NgVNPeqxohBuQ==,type:bool]
                      webhook_url: ENC[AES256_GCM,data:F1jE0Z3ncGCTKh8palKcZLAmSJLFKzlvrMkvAiuCEZip7M2QU7AIeRSIvUCpygYDP5Ffmulg2SNkvD3acxx37ni1uYR9cKXTJCohOXByV5cRGS5uxoT19X5N85xiliTv2RLYYEhXDxwDd0IXIg6UZUF/SNcfgbJ2lg==,iv:o4J1ZzGUQAD+zhwF5b7vrInKD1GkzUEqX3NwUEUae7c=,tag:hDALyBRi4kPWjK+ZgrR9Bw==,type:str]
                      title: ENC[AES256_GCM,data:IcsuIAjExREzmEyN9uBZKjOSu+8FpACOTj8w9Kp9+1eDU6EOvrN8+g==,iv:tttgfJQQmLqhADpcpTKUgFFZ2DjXHA4/43tjroWFyrE=,tag:bq2i7vCvxaTA74cLmH5MmQ==,type:str]
                      message: ENC[AES256_GCM,data:tiwKuGzub2NFUCtChyJx8zwfzuOCqsDeZPAyxt5rookBmWSiRM/sc389,iv:IeEF1oWcCEN9diMPCwXVwdz+Ok50D9Gd5MNeg+2lQ4A=,tag:JXYVCPyUp01Np+NvuYcOIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWHZqTFQ4YkoxaW5uQU5u
            ZXBhWTRsWnNUbkp4RFZLRWRHLzY0WUVhTWpRClp0SXYvSVk5YVU0QWIvYUFxR0dP
            dFBjVUpuaFlUTjhLM2czY1ppakRRUk0KLS0tIFZrN2czZzhXQzVvRXdJb2IyZ0Vu
            eXoyRVZsRFRKaE8xbHpaaHVCc0N3UE0Kr5AHZmlD1Qj1K5CNYhUNmjQJauUVru5Y
            1090t9dRKQ4xQbo6MWkeX+2AE5VVnQBoDLCUQbygRmQgXRJi+NWbJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T09:52:50Z"
    mac: ENC[AES256_GCM,data:BWQfWmz1kOgF4zqt0WrcbiLBUIzDePN8R5lx6CHvRqPGtpuRuMlJKHphEFUPMw8HYgEj24KsNVvDxPi+Nv1g8HNRnCSqlJ8KkCJTabUUP8vnOvYjT8Ts5lJIgzrqGrtGxaPTRPhGHb0LX1NUJo7S+jg6jSSffhcDwH0Cqy/S3R4=,iv:7m2W8K+7s12YR0RqZ12vv0DfSswEZwhCRIbHjnIjCw8=,tag:IZd2HIFHgGGPE5HpcBomJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
