kube-prometheus-stack:
    grafana:
        envRenderSecret:
            GH_CLIENT_ID: ENC[AES256_GCM,data:RlpssC8SwyortGpbrhe62815Zww=,iv:DphD19K3HoPUfYSYXcJia1+hvGRHmCPRBijthACHuTA=,tag:IG+ob2TPqgA0pb2NHCByeA==,type:str]
            GH_CLIENT_SECRET: ENC[AES256_GCM,data:IjgToUJ8klMkzJowhzQguv6UquBLDMzYNQz19J6gbJOI2NMHYfCh+w==,iv:5jMZad4lWVxFM1/ZbT3xEnrs8yRt0OH7OUMJzpEwiWk=,tag:Z0HhfawUQCvDzgH51tGXug==,type:str]
        adminPassword: ENC[AES256_GCM,data:SoODYhHs9g==,iv:olGWogyWA8unQe/kYjsgK4/8Tvhidvh8CissjL2Jt3k=,tag:fLwVfoLLj2YveBAezYjzrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NCtINTdxMFpXYnd3SWFl
            c3hSbHRmWEMxazBzYy9FWlFJMGVYSXBkU0J3CkJyaGNWQll5ZTFScmRqZzhpcmNr
            V2Z5TVYvZ1poME1BTC9VZ2ZKVC9OZ00KLS0tIFNuSGxQWkpqcUR6OFIzK1o3OFRL
            SVUvMlVDMFdUS05vcnhtdE9wTEdjSVUKjQOz/FpmD89uuV/hDxi5OXVrDxCzC8g5
            br4bbgPklnWYJf/T2oOuGLwWYS5lxcxV6ReLXPZyUpuhraMry69i1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T09:52:53Z"
    mac: ENC[AES256_GCM,data:RYzBSrWP807dhwkRbJa9aBShk5B7zcmXKoXvX7g6PabR2qGp0blMRi5BCihO8AUtMdR4bLGTD5Pd5jxOxapUeQztLJgu2xm+cdpX3b86+Dlm1Uhi8abs2oADj8Xp9ryzsUZ4/2KnEuN0Fog66L/Jm2Ha8QZJy1MaZpYWSr48OL8=,iv:SC2SeM4e7h9lFiOdXxKh6l61/+bXdKm10iULKMtJQTE=,tag:CK1J1CbazJmMtBujYyi52Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
