labels: &labels
  env: prod
hostname: &hostname heimdall.mpierce.net

heimdall:

  controller:
    replicas: 1

  common:
    global:
      labels: *labels
    podLabels: *labels
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: heimdall.mpierce.net.
          external-dns.alpha.kubernetes.io/ttl: "10"

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          cert-manager.io/common-name: *hostname
        ingressClassName: traefik
        hosts:
          - host: *hostname
            paths:
              - path: /
        tls:
          - secretName: heimdall-service-secret
            hosts:
              - *hostname

    resources:
      limits:
        cpu: 300m
        memory: 786Mi
      requests:
        cpu: 100m
        memory: 265Mi