---
- name: Reboot Cluster Server
  hosts: server
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        test_command: kubectl get nodes

- name: Reboot Cluster Agents
  hosts: agent
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot: