apiVersion: v2
name: oauth2-proxy
description: A custom parent Helm chart for oauth2-proxy 
dependencies:
- name: oauth2-proxy
  version: &chartVersion 7.1.0
  repository: https://oauth2-proxy.github.io/manifests
version: *chartVersion
