oauth2-proxy:
    config:
        client_id: ENC[AES256_GCM,data:uek1OX04XjQy3BxqZgOQ7DIx8Aw=,iv:YWfoYSY9c2t5GJ4wnPL6PakEGum8JsHF043cyWmhZIw=,tag:7sVBZy1LaZpVTGGMgzKQEw==,type:str]
        client_secret: ENC[AES256_GCM,data:mpqhwI8PaCh6psUE37pekDSXDHuhFbFUOGDUfBlUmCly/94+rARyMw==,iv:crUiTxMcGWfy16o92/R3JEdYB3J6bd63o4yN7EoQ4HY=,tag:6jhuHgm5PhKXZu4V4SCayA==,type:str]
        cookie_secret: ENC[AES256_GCM,data:yrmcdjgCjoYwb4ezmqjzoGMGw+TWWwJusYjeS7aIL0G+pgddxxD0nxszoJk=,iv:DvjzqaX0onki3erjmHJBzfaEM7Epm88BBoiRUJ6ppXs=,tag:yRXt56kffz0wngK3k4kNDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OGF1VzdLclQzcm1WMnQ5
            Y3pjSUdUOE5KZ3lsRzg0OHNyVzFPU1JVYjJBCmFZemVSbHN4L1VmY0c4VDdGYnda
            R0RKSDNWY1hKRGpIdlc4K2NEbDNxak0KLS0tIEc4dkpDekt1TEN0U0pvRVBlZTA4
            eitnUlRMWVFDNWNRdGZuZCtUMW13K1kKShwJBjh5x+Sv9F6dpyXEJbdEVeGnBo3v
            eUN9h1nErWf0JDIfURXtt5RsAAOoJVihjJxkqGW1hGnIw9pE7Spu8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T19:42:06Z"
    mac: ENC[AES256_GCM,data:DG7M/BtZrTqhIVT/nhEITV+W0oIo7zn828tJ7nawWMf2D24VmeXlrs/kq1u7aypUR8lp/BAFO+tAFkjZ41vc+Ijuh70ZVzDK13ZEs9PPIMeI4R0xuJryZ3RMnIhYfwrQD0nza8c1ft84dMbcdf2WOuDTPp3fIDVKFnZHP6M6Atg=,iv:lRpb+BJA+NtYW/qYTYuphE/v3NHQJcSN9NJ/Axc3Avg=,tag:/PuVwJQ8ZNE8CIaNuVwmwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
