kube-prometheus-stack:
  alertmanager:
   config:
    global:
      resolve_timeout: 5m
      http_config:
        follow_redirects: true
        enable_http2: true
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'

      - name: 'null'
    route:
      receiver: 'null'
      group_by: ['alertname', 'job', category]
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 8h
      routes:
      - match:
          severity: critical
        receiver: 'discord_alerts'
        continue: false
      - match:
          severity: warning
        receiver: 'discord_noise'
        continue: false
