kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: "cadvisor"
          scrape_interval: 10s
          scheme: https
          tls_config:
            insecure_skip_verify: true
          static_configs:
            - targets:
                [
                  "cadvisor.nas.mpierce.net",
                ]
        - job_name: "pihole"
          scrape_interval: 15s
          static_configs:
            - targets: ["192.168.178.104:9617"]

        - job_name: "traefik"
          scrape_interval: 15s
          static_configs:
            - targets:
                ["192.168.178.104:8889"]
