annotations:
  artifacthub.io/changes: |-
    - kind: removed
      description: BREAKING - Removed support for the `openvpn` and `wireguard` VPN types.
    - kind: added
      description: Added support for adding serviceMonitors to services.
    - kind: changed
      description: ConfigMap checksum logic now only looks at ConfigMap data
    - kind: changed
      description: Explicitly convert defaultMode to decimal notation in code-server addon.
    - kind: changed
      description: Updated gluetun image to v3.31.1
    - kind: changed
      description: Updated code-server image to v4.7.0
apiVersion: v2
description: Function library for Helm charts
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
keywords:
- common
- library
kubeVersion: '>=1.16.0-0'
maintainers:
- email: me@bjw-s.dev
  name: bjw-s
name: common
type: library
version: 0.2.0
