networks:
  docker-exposed:
    external: true
    name: docker-exposed
    driver: bridge

services:
  buildheim:
    container_name: necesse-buildheim
    image: brammys/necesse-server
    restart: unless-stopped
    ports:
      -  14159:14159/udp
    networks:
      - docker-exposed
    environment:
      MOTD: Welcome to the home Necess Server! Enjoy your grind
      WORLD: buildheim
      PASSWORD: password
      SLOTS: 5
      PAUSE: 1
    volumes:
      - ./srv/buildheim/saves:/necesse/saves
      - ./srv/buildheim/logs:/necesse/logs
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m

  homeheim:
    container_name: necesse-homeheim
    image: brammys/necesse-server
    restart: unless-stopped
    ports:
      -  14160:14159/udp
    networks:
      - docker-exposed
    environment:
      MOTD: Welcome to the home Necess Server! Enjoy your grind
      WORLD: meatgrinder
      PASSWORD: Password
      SLOTS: 5
      PAUSE: 1
    volumes:
      - ./srv/homeheim/saves:/necesse/saves
      - ./srv/homeheim/logs:/necesse/logs
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m

  fooheim:
    container_name: necesse-fooheim
    image: brammys/necesse-server
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    restart: always
    ports:
      -  14161:14159/udp
    environment:
      MOTD: Welcome to the home Necess Server! Enjoy your grind
      WORLD: fooheim
      PASSWORD: password
      SLOTS: 5
      PAUSE: 1
    volumes:
      - ./srv/fooheim/saves:/necesse/saves
      - ./srv/fooheim/logs:/necesse/logs
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m
