---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sockshop.test.mpierce.net.
    external-dns.alpha.kubernetes.io/ttl: "10"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end
