{{- with $.Values.secretEnvVars }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" $ }}-env
  labels: {{ include "labels" $ | nindent 4 }}
data:
  {{- range $k,$v := . }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
