argo-cd:
    configs:
        secret:
            extra:
                dex.github.clientID: ENC[AES256_GCM,data:33DULsgwOL1p8VQo6VQfkb7sdy4=,iv:u1y84EFg7V4iXR0hWSZFQXxwwXbLSXUJzSdHHeNVBmU=,tag:gTpj9tCa5oOg5TOqgJbLdQ==,type:str]
                dex.github.clientSecret: ENC[AES256_GCM,data:xfs7vhth32MUG9UNxB48ieYZMqD+WeEbr7Ne5PX1hwlUcOr6R6/KOg==,iv:7dkmqVafI9wl39XyHVVRwM/OEr7vjzZS5gqd+VyAXb8=,tag:m9FJJNc+t/bNVaBGjfY/ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT2pTOU1aY3lINjhiY0RR
            YzBWeDEyMDliZTNhQUVOalpjanR3MU1DN3pZCkRhWkNqaWluaml2Yjd6YS95YVRT
            VjNKd1F2MzVVNkhBeWx2eFNkWXV5ZEUKLS0tIG9mblB5bEpHN1ZBeXowRVZWY21I
            a1dqN3FTKzB6cEhXT3JZWE02OURIS28KAs0Of65BihGojwx5SXdnDOBSaJiXl1j1
            c1B7xjqlIc7Tmtc1stD7Qn8sA73VeRRz/zV7VFYfqN+WDCSCdodxjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-20T20:11:53Z"
    mac: ENC[AES256_GCM,data:WbA9l9VvmlXMkXyXLyDDSgz3nh1bZwAm/Rvq02DZthO58D8xeQl/sWEBOik014j1pkJNEnKd3FFa0Q0Jdb2tocpKtQn9m0U0yYhCbnjRt4C/v3mZgyFEjeIA3nijKeL4vzqpITtk25g9kicI0WNLY8VdxhqB8kY5nuLZfYeCI7k=,iv:fGXtNw6bXz6mV46vuuagg2xFvX07qKl+v/LoHOt67EE=,tag:Njn0j8wGQek5m0uN8+JkYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
