argo-cd:
    configs:
        secret:
            extra:
                dex.github.clientID: ENC[AES256_GCM,data:22rLUz8aKn+vMtUESJGV5Yy7Ikg=,iv:55rfvRbImwOcgFDsdyNKnOm46gbiD1obRPpQoAvwW5Q=,tag:iTyXEtcqbO+4re6rUFADhA==,type:str]
                dex.github.clientSecret: ENC[AES256_GCM,data:6pFj13WkhDtO/lDA395DRL4AeISemxOMo6wWtHpHAPHBbzpCh0G4Bw==,iv:l681GVa92RuLJSi2XsPsha7BJiqFv2u6/x8tbUjqrw8=,tag:Y6DAsXqjktPR1+93ovpAdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS05mK0Y2L0FYOEFpbksz
            SWlOTFg5b1JYb25scjVtS0d5d3lQT1ROQW5RCm5Qd0ZzZTVpSXREQk9uTXBmc1lM
            bWhGL2tkQWhycWxqWkFYcE1xcm1BcEEKLS0tIEhBeGZJcG9rT1BHQjYyZ0ZrL1M1
            R2NKSFJUZjQzR1dlVEF3WndSQW9YcjgKGz6LcLS9BbUVdOUvTR12Z24tNpmmAQh+
            srGdv3Kz7djsRUwFP1OMiZ7i0lv5P/kYO4nbjUC2XMmVpgMRAj1VUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T18:30:14Z"
    mac: ENC[AES256_GCM,data:3y4pw2m/3GU/9K+26VQaXXCCAX9Ion/z8Unlb3H4KanoxksHBw5BurAxDiaA+/PnqulhUXW39sy3FHHbvfq7BoqfBR/octY6nKmdGbZf3eHGCIxEWUIYffwgGHM93Q/eK3IPxuLJDJoQ9A0E8uHKchMjg1EgheT3lGE49Ol7mp0=,iv:drq2lskaEdiosT5Z3d0tMTXPNf9pmd7C4FozQlqGdtM=,tag:NqnGdc6CosFsW1h3ZRN75A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
