age:
    age_key: ENC[AES256_GCM,data:dXCi7YHVSfi6G2jNd2k16MoBbQHrwMI9IsScQOJyEzFzqYSKXjQoMsi0HFXpz1aVR923g6++e80H7EjfNsVwivSsrFTn3MRn0sDDyfM4/UfmRAA8GeuED0qGa3m6afQwDP2Ucqhv5FOzZXUBl9xTIvY5CifmKTvtK4dt+Fj7AgAPLeXOI3iHyIHxSNdaoRJmlMIZ6S5Rc9f/XAvlEDvuY+SCxrZd8PIqLbXhVNr8TutnnRBddsv5tIN5IfyZ,iv:rsZZooECS+HOJyB5TAm4u26FJRU4jwD5IWXqtRNAJWs=,tag:rC9122bvLAk5eP4DV/PnLg==,type:str]
git:
    sshPublicKey: ENC[AES256_GCM,data:r6KG6rbAwlEUhc4LQ4A6DQkKsgU3/KwDdRy9alkdU0lc/DlxS/GgxXMVFi+0hwJ1jqdhxO/4avgXV46KwyU89LdfQizIwnTBmZewSt2mu0E17L7C8OF5QD6F1PkuAaWKPOwlfYLP/68=,iv:E6xMORPv2GXRc8KdmXZ9hzurjZQpbkKRYT1egStwXwk=,tag:0uqQpRaCKvmU33YZ8OMdmA==,type:str]
argo-cd:
    configs:
        credentialTemplates:
            homelab:
                sshPrivateKey: ENC[AES256_GCM,data:lsb91sWxeinH8wU9Fjya1tEx4UHK9d/2VxXoKX8ebRbgv2LPjCSw/DPVsgudzOl11Tm1eqRL0788AiFDFxSXI265w55maAq4z3QaDX43ZHsc8D3zRsoQAVft0Ow1/7Oe538oMwZ+cE3CFLgPs19hZuffDQ2ECXb2LWvtOWVQfn7Iq9B/Y9U/KcKKd0zDea7qJRZNRytj4Pv1vLoS4Fi1PudiLHkY8lnWaf/0nrdeIZeXVMT9rywfIhrguDSYHGtqsoYYVqhKH2ZdkpguErQsR+cA93/jzokdtzGCB6yLjUj1PrawefZkeFM3VAnt/GRmJKgx2hojET8PL4AeEwVD5bllo4fM3nJfNGEW7AuU8sv+PhQsXWq8BfSnoJiayojgdaV3XmAbAmCEVr81aAQJLkcyMyYnvf7MXVAI4qX5yniky6qS0nhNo1End6qbDosa4c7Y6twIdzTadO9PUkKJ16eM3BE3fszumolwM8GnZlWL1RMqnozIXTW2UUrdE0gwvfwutIar9nxgauKuaag=,iv:Bt9KRsvgwtxDzHSoA3o09c1tDAXyYAMTfJCqn86PB3U=,tag:wqIECQqk866T5/Qf5HMXcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dEt6cEFiUkpkWWRhWUpt
            UU9NSXhyRnI5ZGtlc0JsZDVtMVpUUDNLdjNVCk5WWE9YdTZVRWxURStFdkRUM3Z5
            dE5PdkVpNE9SYzVSeWpZTy9oaThRVkEKLS0tIFg0MTZJNDMvVmxRa0UxZWRXR05B
            T29GR2dac0FoTlJoUEk3VVhRR05RK28KKrzB4j6i8nXYCLBy9R59nFcNq2Daewgl
            5NdHueh9z//P96MDoXAuNT9lEagMeY+rrVIRDTU+Qxjoj8i8hpb5Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-20T20:17:48Z"
    mac: ENC[AES256_GCM,data:yUc8UOUgYNUV1xuYQWQhVl64FT1o9SbTz0ykNHshOXr4IMxgXMMeT/yCIh6vGJ988HEZPou7uegsBe1a43oAGCnt3mN/3rwp6Pi1h0lU564XPAOlwJtYGZesuElH+zTyCoNEGHT3K5kiiyNscYqnQTK2I8e49+GXkpoEnpWJ3YE=,iv:aF/jlerj+Iq2WfnIUMmM4wRYttmPqiVal83TW9sBL/M=,tag:qt70qUQ1TyQ9aTuj7MHG5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
