argo-cd:
    configs:
        secret:
            extra:
                dex.github.clientID: ENC[AES256_GCM,data:FZbno54NzLzbTpjhi5H0itK6yKE=,iv:2Q/CW2PBQCQoskXh7LJqM2m7LZkfncU/SSm7tx0u7lg=,tag:VhUBg6KlaPDb/aCNJeKYYA==,type:str]
                dex.github.clientSecret: ENC[AES256_GCM,data:DDLRGIC+qjwfPLgSCLeva/C1B9tUFXmclmvMLfV9juDuX3pTej4hNg==,iv:iMqE+in73N5fLwm9el/nghLic2vkMQTZx3DmXTPPanE=,tag:aIqoJHVdAqBPNhKCr/imwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UndhblpTOWZKdVd3MlNW
            RmZWSDNmRHBUTUJ2bXdqOHEvUjRTczlVTFFFClVCWHpET05mcyt5WXFVMlNuRkJG
            V2tqNzJOa0gxdnZrODQrekdxMVRrK0kKLS0tIFliSlJxbXlRUzB2c0hPVkRUZEhi
            ODNGSzBZNEgxb0dNNFg5UHNTMVhEN0UKcTivm/G4fV0rsb2yKT/ei7XR7hrodmZ8
            MqFT+39ID8RDBMVfhUPnuyKNzaNdPYOcK4qiRjMk7AqjCzWYTCoisQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T18:30:11Z"
    mac: ENC[AES256_GCM,data:siEWT0wn/QmPEdVgD75fAKLTHcFuCEM/Zn+5D90TQ/qZRxZ7M4yhxgxPj/eiKFkHlLnzMZ8O8NTcePSBvAti9b+bDfpRNo/lBDqbg2etHDiOwI4v9s/SPO/TXYe6ALMLtYQ/mwHyaD1cHT8+SRyWVSQo3xDCd+2rcjYJEVheqPs=,iv:QSs3cfKgMpiHG9PyLIfN2kZG7uTmZ6VOMJHrZk22SX0=,tag:XF3JSV2ygGXctdiNEwqzgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
