labels: &labels
  env: prod

argo-cd:
  global:
    additionalLabels: *labels
    domain: &host argocd.mpierce.net
    image:
      repository: ghcr.io/markdpierce/privatelab/argocd
      tag: v2.10.4

  server:
    ingress:
      enabled: true
      https: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt
        cert-manager.io/common-name: *host
      hostname: *host
      extraTls:
        - secretName: argocd-server-tls
          hosts:
            - *host
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.mpierce.net.
        external-dns.alpha.kubernetes.io/ttl: "10"
      type: LoadBalancer

argocd-apps:
  applications:
    - name: homelab
      namespace: argocd
      project: homelab
      source:
        repoURL: git@github.com:MarkDPierce/privatelab.git
        targetRevision: HEAD
        path: k3s/helm/applications
        helm:
          valueFiles:
            - values.prod.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true