version: '3.9'

networks:
  docker-nonexposed:
    internal: true
    driver: bridge

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    networks:
      - docker-nonexposed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_CLEANUP="true"
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 0 1 * * *
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=${GOTIFYURL}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${GOTIFYTOKEN}
    labels:
      - "env=prod"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          memory: 30m
        reservations:
          memory: 17m
