project: homelab
repo: git@github.com:MarkDPierce/k3s-homelab.git
branch: prod

# My 'production' cluster is still configured and deployed very differently
# I still retain charts due to this as well as this application setup style

apps:
  sockshop:
    valueFiles:
      - values.yaml

  heimdall:
    valueFiles:
      - values.yaml
      - values.prod.yaml

  cert-manager:
   valuesFiles:
    - values.yaml
    - values.prod.yaml
    - secrets://secrets.yaml