REPO := external-dns
REPONAME := $(REPO)
CHARTVER := 1.14.3
REPOURL := https://kubernetes-sigs.github.io/external-dns/
VALUES := -f values.yaml -f secrets.yaml
NAMESPACE := $(REPO)

include ../build.mk
