# If you utilize private regstries. Such as 
mirrors:
  ghcr:
    endpoint:
      - "https://ghcr.io"
configs:
  "ghcr.io":
    auth:
      username: MarkDPierce
      password: <GH PAT FOR REGISTRY ACCESS>