apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
  labels:
      app: {{ template "cert-manager.name" . }}
      app.kubernetes.io/name: {{ template "cert-manager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.clusterIssuer.cloudflare.apiEmail }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    # An empty selector will 'match' all Certificate resources that
    # reference this Issuer.
    - selector: {}
      dns01:
        # providers in the documentation: https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme/dns01/index.html
        cloudflare:
          email: {{ .Values.clusterIssuer.cloudflare.apiEmail }}
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
