{{- range .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .name }}"
  labels:
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .name }}"
      labels:
        {{- with .Values.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .name }}"
          image: ghcr.io/grafana/k6-operator:runner-v0.0.12rc1
          env:
            - name: K6_PROMETHEUS_RW_TREND_STATS
              value: p(95),p(90),p(99),min,max,avg
            #- name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
            #  value: "true"
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: http://prometheus-prometheus.prometheus.svc.cluster.local/api/v1/write
          command:
            ["k6", "run", "-o", "experimental-prometheus-rw", "{{ .runname }}"]
          volumeMounts:
            - name: k6-operator-loadtest
              mountPath: /home/k6
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: k6-operator-loadtest
          configMap:
            name: k6-operator-loadtest
      restartPolicy: Never
{{- end }}
