apiVersion: v1
appVersion: 0.0.11
description: A Helm chart to install the k6-operator
home: https://k6.io
icon: https://raw.githubusercontent.com/grafana/k6-docs/main/static/images/icon.png
keywords:
- load-testing
- smoke-testing
- stress-testing
- soak-testing
- kubernetes
- distributed-testing
kubeVersion: '>=1.16.0-0'
maintainers:
- email: olha@k6.io
  name: yorugac
name: k6-operator
sources:
- https://github.com/grafana/k6-operator
version: 2.0.0
