---
# Metallb address pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipPool.addressPoolName }}
  namespace: {{ .Values.metallb.fullnameOverride }}
  labels: {{- with .Values.metallb.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  addresses:
  - {{ .Values.ipPool.IPAddressPool }}
---
# L2 configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.ipPool.addressPoolName }}
  namespace: {{ .Values.metallb.fullnameOverride }}
  labels: {{- with .Values.metallb.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  ipAddressPools:
  - {{ .Values.ipPool.addressPoolName }}
