labels: &labels
  env: dev

host: &host argocd.dev.mpierce.net

argo-cd:
  global:
    additionalLabels: *labels

  configs:
    cm:
      url: https://argocd.dev.mpierce.net

  server:
    config:
      url: https://argocd.dev.mpierce.net
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - *host
      tls:
        - secretName: argocd-tls
          hosts:
            - *host
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.dev.mpierce.net.
        external-dns.alpha.kubernetes.io/ttl: "10"
