labels: &labels
  env: prod

traefik:
  service:
    spec:
      # Set load balancer external IP
      loadBalancerIP: 192.168.178.220

  logs:
    general:
      level: ERROR

  resources:
    requests:
      cpu: "50m"
      memory: "150Mi"
    limits:
      cpu: "100m"
      memory: "250Mi"
