longhorn:
    defaultSettings:
        backupTarget: ENC[AES256_GCM,data:5gV74BkJF0mUau3qKnCu8MHpHdKY+s4I47NqMVt+xLDjcdz/0VtHpgYl,iv:35o262sPYCSLRxMERFmIfXRV+ZOe0LS6bc/FepC2NW4=,tag:lVeQBl6WKj90sYQklBvZ2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lpgzpxq8p4vczngn94z59aycxjlw53s877hw7jm26el6e9x25prqcjmy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NTJSVDI1QlQ2WG1EdVdT
            OHpJZGE4Zk9KdDdGSTNjb1RWZFU2SkMrR1ZjCjNYL0tUdlZmMHFlY3NHTU81L3RY
            eFJ4UW9UbjBTdzdzS290eDUvcUE5KzAKLS0tIFByZ0tRdTdMUTF4OHBuWmluWFRN
            VG5teUpBWGhYZWtOcDU4VEVTekUyY1UKKjkmHzj2LKuJ4sGhSRy+N2QFFgqLKVK7
            ZALXRo1Fd4Yn4Gb0TU86QvqeIVEqMnwiSN6lDqn5MflsjbeYxpqILg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T19:35:46Z"
    mac: ENC[AES256_GCM,data:eXaq6RJ8fjT8K1AYTxTP5LC+r5g10aenIchtA8cUxGbfsRi0PpoitGainHEZeSr7ZrfDKtC25Sf2mppCAjEW1Wezyq/r2S0p8V0bCQTuJxwtwoK/GO0GAlXx0ngGC6BDPWeMu6Q3Hp2RmEJHk0Og2fHgwhwZgPvOrY5DdMtC+e0=,iv:+CjIIZWjKZmzovwUJ0UcxHMCjmnSc7nTPgklafbddQM=,tag:rT/GpR6rHE+GBPpsPqveKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
