jobs:
  backup:
    heimdall:
      cron: "*/15 * * * *"
      retain: 1
      concurrency: 2
      app: heimdall
      env: prod


longhorn:
  defaultSettings:
    defaultDataPath: /storage
    replicaSoftAntiAffinity: true
    logLevel: "Warn"
    upgradeChecker: false
    
  ingress:
    enabled: true
    ingressClassName: traefik
    host: &hostname longhorn.mpierce.net
    tls: true
    tlsSecret: longhorn-service-tls
    path: /
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt
        #cert-manager.io/common-name: *hostname