# Does not allow custom labels: Wanting a Rancher based app that is not total garbage. That would be nice.
longhorn:
  defaultSetting:
    defaultDataPath: /storage
    storageMinimalAvailablePercentage: 80
    replicaSoftAntiAffinity: true

  persistence:
    defaultClassReplicaCount: 1

  services:
    ui:
      type: LoadBalancer
    manager:
      type: LoadBalancer

