---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.178.107:
    agent:
      hosts:
        192.168.178.108:
        192.168.178.109:
        192.168.178.110:
        192.168.178.111:

#k3s_pi_cluster:
#  children:
#    piserver:
#      hosts:
#        192.168.178.40:
#    piagent:
#      hosts:
#        192.168.178.41:
#        192.168.178.42:
#        192.168.178.43:


  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: ansible
    k3s_version: v1.30.1+k3s1
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: "--disable servicelb --disable traefik"
    extra_agent_args: ""
    cluster_context: k3s-devlab
    token: "changeme!"  # Use ansible vault if you want to keep it secret

  # Optional vars
    # cluster_context: k3s-ansible
    # api_port: 6443
    # k3s_server_location: /var/lib/rancher/k3s
    # systemd_dir: /etc/systemd/system
    # extra_service_envs: [ 'ENV_VAR1=VALUE1', 'ENV_VAR2=VALUE2' ]
    # Manifests or Airgap should be either full paths or relative to the playbook directory.
    # List of locally available manifests to apply to the cluster, useful for PVCs or Traefik modifications.
    # extra_manifests: [ '/path/to/manifest1.yaml', '/path/to/manifest2.yaml' ]
    # airgap_dir: /tmp/k3s-airgap-images
    # user_kubectl: true, by default kubectl is symlinked and configured for use by ansible_user. Set to false to only kubectl via root user.
    # server_config_yaml:  |
      # This is now an inner yaml file. Maintain the indentation.
      # YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
      # See https://docs.k3s.io/installation/configuration#configuration-file
    