labels: &labels
  bar: foo

k6-operator:
  manager:
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi

runner:
  name: k6-runner
  image:
    repository: ghcr.io/grafana/k6-operator
    name: runner-v0.0.12rc1
  prometheus:
    endpoint: http://prom-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090/api/v1/write
    trendStats: p(95),p(90),p(99),min,max,avg
