labels: &labels
  environment: test

k6-operator:
  customLabels: *labels
  podLabels: *labels

jobs:
  - appName: heimdal # The name of the application. Will help filtering in Grafana
    runName: service-test # The name of this run. Will help filtering in Grafana
    runs: 1 # The number of times this job is ran after each completion
    testScript: service-test.js # The loadtest script you wish to execute
    hostname: heimdall.heimdall.svc.cluster.local
    deleteJobAfter: 240

  - appName: sockshop-fe
    runName: front-end
    runs: 1
    testScript: service-test.js
    hostname: front-end.sockshop.svc.cluster.local
    deleteJobAfter: 240

  - appName: traefik
    runName: stress
    runs: 1
    testScript: stress.js
    hostname: traefik.traefik.svc.cluster.local
    deleteJobAfter: 240
