name: Image builder and shipper

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - images/**/*
  push:
    branches:
      - master
      - dev
    paths:
      - images/**/*

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Github Container Reg. Auth
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build Images
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          for file in images/**/Dockerfile ; do
            dir=$(dirname ${file})
            (( $(git diff HEAD~1 --name-only -- $dir | wc -l) == 0 )) && continue
            ( cd $dir ; make build )
          done
        env:
          DOCKER_BUILDKIT: "1"
      - name: Build and push all changed images
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          for file in images/**/Dockerfile ; do
            dir=$(dirname ${file})
            (( $(git diff HEAD~1 --name-only -- $dir | wc -l) == 0 )) && continue
            ( cd $dir ; make push )
          done
        env:
          DOCKER_BUILDKIT: "1"
      - name: Build and push all images
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master' }}
        run: |
          for file in images/**/Dockerfile ; do
            dir=$(dirname ${file})
            ( cd $dir ; make push )
          done
        env:
          DOCKER_BUILDKIT: "1"
